### ISSUE TITLE
이상하게 다른 채널 댓글은 안 지워지는데 저자님 채널에 제가 글을 쓰면 지워집니다. 그래서 여기에 질문을 남깁니다.

### ISSUE THREAD

**Issue by coboooo** [junsuk5/android-first-book#2]
https://github.com/junsuk5/android-first-book/blob/master/MyFirstApp/src/main/java/com/example/myfirstapp/DisplayMessageActivity.java 이 코드가 완성된 게 아닌 거 같아서요. 제가 책을 보고 따라한 거랑 비교를 해보고 싶어서 그렇습니다.

**Comment by junsuk5** [comment]
혹시 책 몇 장 하고 계신 것인가요? 2장이라면 특별히 코드를 작성할 부분이 없는 것 같습니다. 단순히 프로젝트 작성한 한 것이라서요

**Comment by coboooo** [comment]
3장입니다. 2장이랑 3장 앱의 이름이 My First App으로 똑같아서 좀 헷갈렸어요. 3장의 앱을 찾고 있어요.

**Comment by junsuk5** [comment]
3장의 경우에 제가 코드를 빼 먹고 올렸나 보네요. 특별한 내용은 없고 책 대로 작성해서 동작이 잘 되면 됩니다. 워낙 간단한 코드라서 아직까지 문의는 없었나 봐요. 혹시 문제 있으시면 다시 말씀해 주세요. 제가 시간 날 때 코드를 작성해 넣거나 하겠습니다.

**Comment by coboooo** [comment]
> 3장의 경우에 제가 코드를 빼 먹고 올렸나 보네요. 특별한 내용은 없고 책 대로 작성해서 동작이 잘 되면 됩니다. 워낙 간단한 코드라서 아직까지 문의는 없었나 봐요. 혹시 문제 있으시면 다시 말씀해 주세요. 제가 시간 날 때 코드를 작성해 넣거나 하겠습니다.

답변 감사합니다. 초보자라서 따라해도 자꾸 헷갈려서 제 코드와 비교를 해보려고 그랬습니다. 이제는 해결이 되었습니다. 답변 감사드립니다. ㅎㅎ
